trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: AppDeploymentSettings
  - name: imageName
    value: 'link-sharing-app'
  - name: containerAppName
    value: 'link-sharing-app'

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Build and push image'
            inputs:
              containerRegistry: 'AzureContainerRegistryConnection'
              repository: '$(acrName).azurecr.io/$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                latest

  - stage: Deploy
    displayName: Deploy to Azure Container Apps
    dependsOn: Build
    jobs:
      - job: DeployContainerApp
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            displayName: 'Update Container App Image'
            inputs:
              azureSubscription: 'AzureServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az containerapp update \
                  --name $(containerAppName) \
                  --resource-group $(resourceGroup) \
                  --image $(acrName).azurecr.io/$(imageName):latest
